'use strict';

/**
 * Wikipedia veri setinde bulunmayan alanlar burada elle tanımlandı:
 * yönetmen, süre (dakika) ve Türkçe kısa açıklama.
 * Anahtar = filmin orijinal adı.
 */
module.exports = {
  "The Godfather": { director: "Francis Ford Coppola", runtime: 175, overviewTr: "Mafya babası Vito Corleone imparatorluğunu devrederken, ailenin en uzak duran oğlu Michael istemeden bu düzenin merkezine çekilir." },
  "Star Wars": { director: "George Lucas", runtime: 121, overviewTr: "Çiftlikte büyüyen Luke Skywalker, bir prensesi kurtarmak ve İmparatorluk'a karşı savaşmak için galaksiye açılır." },
  "Alien": { director: "Ridley Scott", runtime: 117, overviewTr: "Ticari bir uzay gemisinin mürettebatı, gemiye sızan ölümcül bir yaratıkla hayatta kalma mücadelesine girer." },
  "The Shining": { director: "Stanley Kubrick", runtime: 146, overviewTr: "Kış boyunca ıssız bir otele bekçi olarak yerleşen yazar, yavaş yavaş akıl sağlığını yitirir." },
  "Blade Runner": { director: "Ridley Scott", runtime: 117, overviewTr: "Distopik Los Angeles'ta bir avcı, kaçak yapay insanları bulmakla görevlendirilir ve insan olmanın ne demek olduğunu sorgular." },
  "Back to the Future": { director: "Robert Zemeckis", runtime: 116, overviewTr: "Genç Marty McFly, çılgın bir bilim insanının zaman makinesiyle 1955'e gider ve kendi varlığını tehlikeye atar." },
  "Die Hard": { director: "John McTiernan", runtime: 132, overviewTr: "Bir gökdelende rehin alınan çalışanları kurtarmak, tek başına kalan New Yorklu polis John McClane'e düşer." },
  "Goodfellas": { director: "Martin Scorsese", runtime: 146, overviewTr: "Henry Hill'in çocukluğundan itibaren mafya düzeni içinde yükselişi ve çöküşü anlatılır." },
  "The Silence of the Lambs": { director: "Jonathan Demme", runtime: 118, overviewTr: "Acemi FBI ajanı Clarice Starling, bir seri katili yakalamak için mahkûm psikiyatrist Hannibal Lecter'dan yardım ister." },
  "Terminator 2: Judgment Day": { director: "James Cameron", runtime: 137, overviewTr: "Gelecekten gönderilen bir robot, bu kez insanlığın müstakbel liderini korumakla görevlidir." },
  "Jurassic Park": { director: "Steven Spielberg", runtime: 127, overviewTr: "Klonlanmış dinozorlarla kurulan tema parkı, güvenlik sistemleri çökünce ölümcül bir tuzağa dönüşür." },
  "Pulp Fiction": { director: "Quentin Tarantino", runtime: 154, overviewTr: "Los Angeles yeraltında geçen, birbirine bağlanan birkaç hikâye zaman sırası bozularak anlatılır." },
  "The Shawshank Redemption": { director: "Frank Darabont", runtime: 142, overviewTr: "İşlemediği bir cinayetten hüküm giyen Andy Dufresne, hapishanede umudunu ve dostluğunu korumaya çalışır." },
  "Forrest Gump": { director: "Robert Zemeckis", runtime: 142, overviewTr: "Saf yürekli Forrest Gump'ın hayatı, Amerikan tarihinin dönüm noktalarına tesadüfen tanık olarak geçer." },
  "The Lion King": { director: "Roger Allers, Rob Minkoff", runtime: 88, overviewTr: "Babasının ölümünden sonra kaçan aslan yavrusu Simba, büyüdüğünde tahtını geri almak için döner." },
  "Seven": { director: "David Fincher", runtime: 127, overviewTr: "İki dedektif, yedi ölümcül günahı tek tek sahneleyen bir seri katilin peşine düşer." },
  "Toy Story": { director: "John Lasseter", runtime: 81, overviewTr: "Kovboy oyuncak Woody, eve yeni gelen uzay askeri Buzz Lightyear ile önce rekabet eder, sonra dost olur." },
  "Heat": { director: "Michael Mann", runtime: 170, overviewTr: "Profesyonel bir soyguncu ile onu yakalamaya kafayı takmış bir dedektifin karşılıklı satrancı." },
  "Titanic": { director: "James Cameron", runtime: 194, year: 1997, overviewTr: "Farklı sınıflardan iki gencin Titanik'te başlayan aşkı, geminin batışıyla trajediye dönüşür." },
  "The Big Lebowski": { director: "Joel Coen", runtime: 117, overviewTr: "Kimlik karışıklığı yüzünden hayatı alt üst olan tembel bowlingci Dude, absürt bir fidye olayının ortasında kalır." },
  "The Matrix": { director: "Lana Wachowski, Lilly Wachowski", runtime: 136, overviewTr: "Bir yazılımcı, yaşadığı dünyanın makineler tarafından kurulmuş bir simülasyon olduğunu öğrenir." },
  "Fight Club": { director: "David Fincher", runtime: 139, overviewTr: "Uykusuzluk çeken bir ofis çalışanı, karizmatik Tyler Durden ile yeraltı dövüş kulübü kurar." },
  "The Sixth Sense": { director: "M. Night Shyamalan", runtime: 107, overviewTr: "Çocuk psikoloğu, ölüleri gördüğünü söyleyen küçük bir hastaya yardım etmeye çalışır." },
  "Gladiator": { director: "Ridley Scott", runtime: 155, overviewTr: "İhanete uğrayan Romalı general Maximus, köleliğe düşüp arenada intikamını almak için savaşır." },
  "Memento": { director: "Christopher Nolan", runtime: 113, overviewTr: "Kısa süreli hafızasını kaybeden bir adam, notlar ve dövmelerle eşinin katilini arar." },
  "Shrek": { director: "Andrew Adamson, Vicky Jenson", runtime: 90, overviewTr: "Huysuz dev Shrek, bataklığını geri alabilmek için bir prensesi kurtarma görevini üstlenir." },
  "Monsters, Inc.": { director: "Pete Docter", runtime: 92, overviewTr: "Çocukları korkutarak enerji üreten canavarlar şehrine küçük bir kız sızınca bütün düzen alt üst olur." },
  "The Lord of the Rings: The Fellowship of the Ring": { director: "Peter Jackson", runtime: 178, overviewTr: "Hobbit Frodo, dünyayı yok edebilecek Yüzük'ü imha etmek üzere kurulan kardeşlikle yola çıkar." },
  "The Lord of the Rings: The Return of the King": { director: "Peter Jackson", runtime: 201, overviewTr: "Orta Dünya'nın kaderi son büyük savaşta ve Frodo'nun Hüküm Dağı'na ulaşmasında belirlenir." },
  "Kill Bill: Volume 1": { director: "Quentin Tarantino", runtime: 111, overviewTr: "Düğününde vurulan eski suikastçı, komadan uyandıktan sonra intikam listesini tek tek uygular." },
  "Finding Nemo": { director: "Andrew Stanton", runtime: 100, overviewTr: "Oğlu kaçırılan endişeli palyaço balığı Marlin, okyanusu boydan boya geçerek onu aramaya çıkar." },
  "Eternal Sunshine of the Spotless Mind": { director: "Michel Gondry", runtime: 108, overviewTr: "Ayrılan bir çift, birbirlerine dair anıları sildirmeye karar verir; ama hafıza kolay teslim olmaz." },
  "Batman Begins": { director: "Christopher Nolan", runtime: 140, overviewTr: "Bruce Wayne'in korkularıyla yüzleşip Gotham'ın karanlık koruyucusuna dönüşme hikâyesi." },
  "The Departed": { director: "Martin Scorsese", runtime: 151, overviewTr: "Polis teşkilatındaki bir mafya köstebeği ile mafyanın içindeki bir gizli polis birbirini arar." },
  "No Country for Old Men": { director: "Joel Coen, Ethan Coen", runtime: 122, overviewTr: "Çölde bulduğu para dolu çantayı alan bir adam, acımasız bir tetikçinin hedefi hâline gelir." },
  "Ratatouille": { director: "Brad Bird", runtime: 111, overviewTr: "Yemek yapmayı tutkuyla seven bir fare, Paris'in ünlü bir restoranında gizlice şeflik yapar." },
  "There Will Be Blood": { director: "Paul Thomas Anderson", runtime: 158, overviewTr: "Petrol arayıcısı Daniel Plainview'ın hırsı, onu servete ve aynı zamanda tam bir yalnızlığa sürükler." },
  "The Dark Knight": { director: "Christopher Nolan", runtime: 152, overviewTr: "Batman, Gotham'ı kaosa sürükleyen Joker karşısında hem şehrin hem kendi ahlakının sınırlarını zorlar." },
  "WALL-E": { director: "Andrew Stanton", runtime: 98, overviewTr: "Terk edilmiş Dünya'da çöp toplayan küçük robot WALL-E, gelen keşif robotu EVE'ye âşık olur." },
  "Up": { director: "Pete Docter", runtime: 96, overviewTr: "Yaşlı Carl, evini binlerce balonla havalandırıp çocukluk hayalindeki yolculuğa çıkar; yanında da bir izci vardır." },
  "Avatar": { director: "James Cameron", runtime: 162, overviewTr: "Pandora gezegenine gönderilen felçli asker, Na'vi halkının içinde yeni bir hayat ve yeni bir taraf bulur." },
  "District 9": { director: "Neill Blomkamp", runtime: 112, overviewTr: "Johannesburg'da kamplara kapatılan uzaylılarla ilgilenen bir memur, kendisi de dönüşmeye başlar." },
  "Inception": { director: "Christopher Nolan", runtime: 148, overviewTr: "Rüyalara girip fikir çalan bir ekip, bu kez tersine bir görev üstlenir: hedefin zihnine fikir yerleştirmek." },
  "Toy Story 3": { director: "Lee Unkrich", runtime: 103, overviewTr: "Andy üniversiteye giderken oyuncaklar bir kreşe bağışlanır ve yeni bir kaçış planı yapmak zorunda kalırlar." },
  "The Social Network": { director: "David Fincher", runtime: 120, overviewTr: "Facebook'un yurt odasında doğuşu, arkadaşlıkların dava dosyalarına dönüşmesiyle birlikte anlatılır." },
  "Drive": { director: "Nicolas Winding Refn", runtime: 100, overviewTr: "Gündüz dublör, gece kaçış şoförü olan sessiz bir adam, komşusunu korumak için tehlikeli bir işe bulaşır." },
  "The Avengers": { director: "Joss Whedon", runtime: 143, overviewTr: "Dünya'yı tehdit eden bir istilaya karşı birbirinden farklı süper kahramanlar ilk kez bir araya gelir." },
  "Django Unchained": { director: "Quentin Tarantino", runtime: 165, overviewTr: "Özgürlüğüne kavuşan Django, bir ödül avcısıyla birlikte eşini kurtarmak için yola çıkar." },
  "The Wolf of Wall Street": { director: "Martin Scorsese", runtime: 180, overviewTr: "Borsacı Jordan Belfort'un dolandırıcılıkla kurduğu imparatorluğun baş döndürücü yükselişi ve çöküşü." },
  "Gravity": { director: "Alfonso Cuarón", runtime: 91, overviewTr: "Uzay yürüyüşü sırasında gemileri parçalanan iki astronot, boşlukta hayatta kalmaya çalışır." },
  "Her": { director: "Spike Jonze", runtime: 126, overviewTr: "Yalnız bir adam, sesli yapay zekâ işletim sistemine âşık olur ve aşkın tanımını yeniden sorgular." },
  "Interstellar": { director: "Christopher Nolan", runtime: 169, overviewTr: "Tükenen Dünya'yı kurtarmak için bir grup astronot, solucan deliğinden geçerek yeni bir yuva arar." },
  "Whiplash": { director: "Damien Chazelle", runtime: 107, overviewTr: "Yetenekli bir davulcu ile acımasız hocası arasındaki mükemmellik takıntısı ikisini de sınırına iter." },
  "Guardians of the Galaxy": { director: "James Gunn", runtime: 121, overviewTr: "Galaksinin dağınık kaçakları, güçlü bir küreyi korumak için istemeden bir ekibe dönüşür." },
  "Mad Max: Fury Road": { director: "George Miller", runtime: 120, overviewTr: "Çölleşmiş bir dünyada Max ve Furiosa, zorbadan kaçan kadınlarla birlikte upuzun bir kovalamacaya girer." },
  "Inside Out": { director: "Pete Docter", runtime: 95, overviewTr: "Taşınmak zorunda kalan küçük Riley'nin zihninde Neşe ve Üzüntü, kontrol merkezinden ayrı düşer." },
  "The Martian": { director: "Ridley Scott", runtime: 144, overviewTr: "Mars'ta yalnız kalan bir botanikçi, kurtarılana kadar bilimle hayatta kalmanın yolunu arar." },
  "Sicario": { director: "Denis Villeneuve", runtime: 121, overviewTr: "Bir FBI ajanı, sınırdaki uyuşturucu savaşında kuralların çoktan rafa kaldırıldığı bir operasyona dahil edilir." },
  "Arrival": { director: "Denis Villeneuve", runtime: 116, overviewTr: "Dünya'ya inen uzay gemileriyle iletişim kurmakla görevlendirilen dilbilimci, zamanı bambaşka görmeye başlar." },
  "La La Land": { director: "Damien Chazelle", runtime: 128, overviewTr: "Los Angeles'ta bir caz piyanisti ile oyuncu adayının aşkı, hayalleriyle sınanır." },
  "Get Out": { director: "Jordan Peele", runtime: 104, overviewTr: "Sevgilisinin ailesini ziyarete giden genç adam, o evde çok daha karanlık bir şeyin döndüğünü fark eder." },
  "Blade Runner 2049": { director: "Denis Villeneuve", runtime: 164, overviewTr: "Yeni nesil bir avcı, ortaya çıkardığı sır yüzünden kendi geçmişini ve kimliğini sorgulamaya başlar." },
  "Coco": { director: "Lee Unkrich", runtime: 105, overviewTr: "Müzik yasaklı bir ailede büyüyen Miguel, Ölüler Diyarı'na geçip ailesinin gerçek hikâyesini öğrenir." },
  "Dunkirk": { director: "Christopher Nolan", runtime: 106, overviewTr: "Dunkirk sahilinde kıstırılan askerlerin tahliyesi, kara, deniz ve hava olmak üzere üç ayrı zaman diliminden anlatılır." },
  "Spider-Man: Into the Spider-Verse": { director: "Bob Persichetti, Peter Ramsey, Rodney Rothman", runtime: 117, overviewTr: "Miles Morales, farklı evrenlerden gelen Örümcek Adamlarla tanışır ve kendi kahramanlığını bulur." },
  "Black Panther": { director: "Ryan Coogler", runtime: 134, overviewTr: "Wakanda'nın yeni kralı T'Challa, tahtına ve ülkesinin geleceğine dair bir meydan okumayla yüzleşir." },
  "Avengers: Infinity War": { director: "Anthony Russo, Joe Russo", runtime: 149, overviewTr: "Thanos, Sonsuzluk Taşlarını toplarken kahramanlar evrenin yarısını kurtarmak için dağınık cephelerde savaşır." },
  "A Quiet Place": { director: "John Krasinski", runtime: 90, overviewTr: "Sese göre avlanan yaratıkların istila ettiği dünyada bir aile, tek kelime etmeden hayatta kalmaya çalışır." },
  "Joker": { director: "Todd Phillips", runtime: 122, overviewTr: "Dışlanmış bir stand-up heveslisi olan Arthur Fleck'in adım adım Joker'e dönüşmesi anlatılır." },
  "1917": { director: "Sam Mendes", runtime: 119, overviewTr: "Birinci Dünya Savaşı'nda iki genç asker, binlerce kişiyi kurtaracak bir mesajı zamanında ulaştırmak zorundadır." },
  "Avengers: Endgame": { director: "Anthony Russo, Joe Russo", runtime: 181, overviewTr: "Yenilgiden sonra geriye kalan kahramanlar, kaybettiklerini geri getirmek için son bir plan yapar." },
  "Knives Out": { director: "Rian Johnson", runtime: 130, overviewTr: "Ünlü bir yazarın şüpheli ölümü, çıkarcı ailesinin ortasında zekice bir dedektiflik oyununa dönüşür." },
  "Soul": { director: "Pete Docter", runtime: 100, overviewTr: "Caz müzisyeni Joe, hayalindeki konser gününde ruhunu kaybeder ve yaşamanın anlamını yeniden keşfeder." },
  "Tenet": { director: "Christopher Nolan", runtime: 150, overviewTr: "Zamanı tersine çevirebilen bir teknolojiyle karşılaşan ajan, üçüncü bir dünya savaşını önlemeye çalışır." },
  "Dune": { director: "Denis Villeneuve", runtime: 155, overviewTr: "Paul Atreides, ailesinin çöl gezegeni Arrakis'te üstlendiği görevle birlikte kendi kaderiyle yüzleşir." },
  "Spider-Man: No Way Home": { director: "Jon Watts", runtime: 148, overviewTr: "Kimliği ifşa olan Peter Parker'ın büyüyle düzeltme çabası, evrenler arası bir kapıyı aralar." },
  "Everything Everywhere All at Once": { director: "Daniel Kwan, Daniel Scheinert", runtime: 139, overviewTr: "Çamaşırhane işleten bir kadın, paralel evrenlerdeki hayatlarına bağlanarak ailesini ve kendini kurtarmaya çalışır." },
  "Top Gun: Maverick": { director: "Joseph Kosinski", runtime: 130, overviewTr: "Efsanevi pilot Maverick, imkânsız bir görev için yeni nesil pilotları eğitmek üzere geri döner." },
  "The Batman": { director: "Matt Reeves", runtime: 176, overviewTr: "Kariyerinin başındaki Batman, Gotham'ın yozlaşmasını hedef alan Bilmececi'nin bulmacalarını çözmeye çalışır." },
  "Oppenheimer": { director: "Christopher Nolan", runtime: 180, overviewTr: "Atom bombasını geliştiren J. Robert Oppenheimer'ın zaferi ve sonrasında ödediği vicdan bedeli." },
  "Barbie": { director: "Greta Gerwig", runtime: 114, overviewTr: "Barbie Diyarı'ndan gerçek dünyaya adım atan Barbie, mükemmelliğin ötesinde kim olduğunu keşfeder." },
  "Spider-Man: Across the Spider-Verse": { director: "Joaquim Dos Santos, Kemp Powers, Justin K. Thompson", runtime: 140, overviewTr: "Miles, örümcek evrenlerinin kaderini belirleyen bir kurala karşı çıkarak kendi yolunu çizer." },
  "Saving Private Ryan": { director: "Steven Spielberg", runtime: 169, overviewTr: "Normandiya çıkarmasının ardından bir müfreze, tek hayatta kalan kardeşi bulup eve göndermekle görevlendirilir." },
  "The Truman Show": { director: "Peter Weir", runtime: 103, overviewTr: "Truman, doğduğundan beri yayınlanan bir televizyon programının içinde yaşadığını yavaş yavaş fark eder." },
  "Iron Man": { director: "Jon Favreau", runtime: 126, overviewTr: "Silah tüccarı Tony Stark, esaretten kurtulmak için yaptığı zırhla birlikte tamamen yeni bir insana dönüşür." },
};
